services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: frontend
    restart: unless-stopped
    networks:
      - hewpao-frontend-network

  caddy:
    image: caddy:2.9.1-alpine
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
    networks:
      - hewpao-frontend-network
    depends_on:
      - app

networks:
  hewpao-frontend-network:
    driver: bridge
