name: "Develop CI"
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["develop"]
  push:
    branches: ["develop"]
permissions:
  contents: read
env:
  APP_NAME: "hewpao-s-frontend"
jobs:
  build:
    name: "Build Dockerfile"
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Build"
        run: |-
          IMAGE_TAG="${GITHUB_REF#refs/*/}"
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${IMAGE_TAG}"

          docker build -f Dockerfile -t "${IMAGE_NAME}" .
